"""initial_schema

Revision ID: b5a2a35738e2
Revises:
Create Date: 2026-07-03 23:25:07.472992

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b5a2a35738e2'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_id'), ['id'], unique=False)

    op.create_table('categories',
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('favorites',
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_favorites_type_id')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_id'), ['id'], unique=False)

    op.create_table('providers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider_type', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=1024), nullable=False),
    sa.Column('api_version', sa.String(length=50), nullable=False),
    sa.Column('deployment_chat', sa.String(length=100), nullable=True),
    sa.Column('deployment_chat_mini', sa.String(length=100), nullable=True),
    sa.Column('deployment_embedding', sa.String(length=100), nullable=True),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_providers_id'), ['id'], unique=False)

    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('tags',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tags_id'), ['id'], unique=False)

    op.create_table('variables',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=50), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Integer(), nullable=False),
    sa.Column('is_system', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'scope', name='uq_variables_name_scope')
    )
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variables_id'), ['id'], unique=False)

    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_id'), ['id'], unique=False)

    op.create_table('analytics_events',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('event_data', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analytics_events_id'), ['id'], unique=False)

    op.create_table('contexts',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_contexts_workspace_slug')
    )
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contexts_id'), ['id'], unique=False)

    op.create_table('conversations',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('provider_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['providers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_id'), ['id'], unique=False)

    op.create_table('journals',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.String(length=50), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_id'), ['id'], unique=False)

    op.create_table('templates',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('template_type', sa.String(length=50), nullable=False),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('default_variables', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Integer(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'slug', name='uq_templates_workspace_slug')
    )
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_templates_id'), ['id'], unique=False)

    op.create_table('workspace_settings',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'key', name='uq_workspace_settings_workspace_key')
    )
    with op.batch_alter_table('workspace_settings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_settings_id'), ['id'], unique=False)

    op.create_table('workspace_variables',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('variable_id', sa.String(length=36), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'variable_id', name='uq_workspace_variables_workspace_variable')
    )
    with op.batch_alter_table('workspace_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspace_variables_id'), ['id'], unique=False)

    op.create_table('context_dependencies',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', name='uq_context_dependencies_source_target')
    )
    with op.batch_alter_table('context_dependencies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_dependencies_id'), ['id'], unique=False)

    op.create_table('context_embeddings',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_id', 'model_name', name='uq_context_embeddings_id_model')
    )
    with op.batch_alter_table('context_embeddings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_embeddings_id'), ['id'], unique=False)

    op.create_table('context_health_scores',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('overall_health', sa.Float(), nullable=False),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('usage_score', sa.Float(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('issues', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_health_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_health_scores_id'), ['id'], unique=False)

    op.create_table('context_tags',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('tag_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('context_id', 'tag_id')
    )
    op.create_table('context_versions',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('context_id', 'version_number', name='uq_context_versions_id_number')
    )
    with op.batch_alter_table('context_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_versions_id'), ['id'], unique=False)

    op.create_table('learning_records',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('analysis', sa.Text(), nullable=False),
    sa.Column('missing_contexts', sa.Text(), nullable=True),
    sa.Column('success_factors', sa.Text(), nullable=True),
    sa.Column('failure_factors', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('applied', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_learning_records_id'), ['id'], unique=False)

    op.create_table('messages',
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('finish_reason', sa.String(length=100), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_id'), ['id'], unique=False)

    op.create_table('prompt_runs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('template_id', sa.String(length=36), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=False),
    sa.Column('compiled_prompt', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('validation_passed', sa.Integer(), nullable=False),
    sa.Column('validation_errors', sa.Text(), nullable=True),
    sa.Column('optimization_applied', sa.Integer(), nullable=False),
    sa.Column('variables_used', sa.Text(), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_runs_id'), ['id'], unique=False)

    op.create_table('template_variables',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('variable_id', sa.String(length=36), nullable=False),
    sa.Column('is_required', sa.Integer(), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['variable_id'], ['variables.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id', 'variable_id', 'id')
    )
    with op.batch_alter_table('template_variables', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_variables_id'), ['id'], unique=False)

    op.create_table('template_versions',
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('schema', sa.Text(), nullable=True),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id', 'version_number', name='uq_template_versions_id_number')
    )
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_template_versions_id'), ['id'], unique=False)

    op.create_table('context_candidates',
    sa.Column('learning_record_id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('suggested_title', sa.String(length=255), nullable=False),
    sa.Column('suggested_content', sa.Text(), nullable=False),
    sa.Column('suggested_type', sa.String(length=50), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['learning_record_id'], ['learning_records.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_candidates_id'), ['id'], unique=False)

    op.create_table('context_usages',
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('prompt_run_id', sa.String(length=36), nullable=True),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=False),
    sa.Column('was_helpful', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('context_usages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_context_usages_id'), ['id'], unique=False)

    op.create_table('prompt_contexts',
    sa.Column('prompt_run_id', sa.String(length=36), nullable=False),
    sa.Column('context_id', sa.String(length=36), nullable=False),
    sa.Column('rank_position', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('was_auto_included', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['context_id'], ['contexts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_run_id', 'context_id', name='uq_prompt_contexts_run_context')
    )
    with op.batch_alter_table('prompt_contexts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_contexts_id'), ['id'], unique=False)

    op.create_table('prompt_scores',
    sa.Column('prompt_run_id', sa.String(length=36), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('clarity_score', sa.Float(), nullable=True),
    sa.Column('specificity_score', sa.Float(), nullable=True),
    sa.Column('completeness_score', sa.Float(), nullable=True),
    sa.Column('consistency_score', sa.Float(), nullable=True),
    sa.Column('efficiency_score', sa.Float(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt_run_id', name='uq_prompt_scores_run')
    )
    with op.batch_alter_table('prompt_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_scores_id'), ['id'], unique=False)

    op.create_table('prompt_versions',
    sa.Column('prompt_run_id', sa.String(length=36), nullable=False),
    sa.Column('version_label', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prompt_run_id'], ['prompt_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prompt_versions_id'), ['id'], unique=False)

    # ── Create FTS5 Virtual Tables and Triggers ──────────────────────
    op.execute(sa.text("""
        CREATE VIRTUAL TABLE contexts_fts USING fts5(
            title,
            content,
            context_type,
            content='contexts',
            content_rowid='rowid',
            tokenize='porter unicode61 remove_diacritics 2'
        );
    """))

    op.execute(sa.text("""
        CREATE TRIGGER contexts_ai AFTER INSERT ON contexts BEGIN
            INSERT INTO contexts_fts(rowid, title, content, context_type)
            VALUES (new.rowid, new.title, new.content, new.context_type);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER contexts_au AFTER UPDATE ON contexts BEGIN
            INSERT INTO contexts_fts(contexts_fts, rowid, title, content, context_type)
            VALUES ('delete', old.rowid, old.title, old.content, old.context_type);
            INSERT INTO contexts_fts(rowid, title, content, context_type)
            VALUES (new.rowid, new.title, new.content, new.context_type);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER contexts_ad AFTER DELETE ON contexts BEGIN
            INSERT INTO contexts_fts(contexts_fts, rowid, title, content, context_type)
            VALUES ('delete', old.rowid, old.title, old.content, old.context_type);
        END;
    """))

    op.execute(sa.text("""
        CREATE VIRTUAL TABLE templates_fts USING fts5(
            title,
            description,
            content,
            content='templates',
            content_rowid='rowid',
            tokenize='porter unicode61 remove_diacritics 2'
        );
    """))

    op.execute(sa.text("""
        CREATE TRIGGER templates_ai AFTER INSERT ON templates BEGIN
            INSERT INTO templates_fts(rowid, title, description, content)
            VALUES (new.rowid, new.title, new.description, new.content);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER templates_au AFTER UPDATE ON templates BEGIN
            INSERT INTO templates_fts(templates_fts, rowid, title, description, content)
            VALUES ('delete', old.rowid, old.title, old.description, old.content);
            INSERT INTO templates_fts(rowid, title, description, content)
            VALUES (new.rowid, new.title, new.description, new.content);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER templates_ad AFTER DELETE ON templates BEGIN
            INSERT INTO templates_fts(templates_fts, rowid, title, description, content)
            VALUES ('delete', old.rowid, old.title, old.description, old.content);
        END;
    """))

    op.execute(sa.text("""
        CREATE VIRTUAL TABLE messages_fts USING fts5(
            content,
            content='messages',
            content_rowid='rowid',
            tokenize='porter unicode61 remove_diacritics 2'
        );
    """))

    op.execute(sa.text("""
        CREATE TRIGGER messages_ai AFTER INSERT ON messages BEGIN
            INSERT INTO messages_fts(rowid, content)
            VALUES (new.rowid, new.content);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER messages_au AFTER UPDATE ON messages BEGIN
            INSERT INTO messages_fts(messages_fts, rowid, content)
            VALUES ('delete', old.rowid, old.content);
            INSERT INTO messages_fts(rowid, content)
            VALUES (new.rowid, new.content);
        END;
    """))

    op.execute(sa.text("""
        CREATE TRIGGER messages_ad AFTER DELETE ON messages BEGIN
            INSERT INTO messages_fts(messages_fts, rowid, content)
            VALUES ('delete', old.rowid, old.content);
        END;
    """))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ── Drop FTS5 Virtual Tables and Triggers ────────────────────────
    op.execute(sa.text("DROP TRIGGER IF EXISTS contexts_ai;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS contexts_au;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS contexts_ad;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS templates_ai;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS templates_au;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS templates_ad;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS messages_ai;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS messages_au;"))
    op.execute(sa.text("DROP TRIGGER IF EXISTS messages_ad;"))

    op.execute(sa.text("DROP TABLE IF EXISTS contexts_fts;"))
    op.execute(sa.text("DROP TABLE IF EXISTS templates_fts;"))
    op.execute(sa.text("DROP TABLE IF EXISTS messages_fts;"))

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prompt_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_versions_id'))

    op.drop_table('prompt_versions')
    with op.batch_alter_table('prompt_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_scores_id'))

    op.drop_table('prompt_scores')
    with op.batch_alter_table('prompt_contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_contexts_id'))

    op.drop_table('prompt_contexts')
    with op.batch_alter_table('context_usages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_usages_id'))

    op.drop_table('context_usages')
    with op.batch_alter_table('context_candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_candidates_id'))

    op.drop_table('context_candidates')
    with op.batch_alter_table('template_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_versions_id'))

    op.drop_table('template_versions')
    with op.batch_alter_table('template_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_template_variables_id'))

    op.drop_table('template_variables')
    with op.batch_alter_table('prompt_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prompt_runs_id'))

    op.drop_table('prompt_runs')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_id'))

    op.drop_table('messages')
    with op.batch_alter_table('learning_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_learning_records_id'))

    op.drop_table('learning_records')
    with op.batch_alter_table('context_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_versions_id'))

    op.drop_table('context_versions')
    op.drop_table('context_tags')
    with op.batch_alter_table('context_health_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_health_scores_id'))

    op.drop_table('context_health_scores')
    with op.batch_alter_table('context_embeddings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_embeddings_id'))

    op.drop_table('context_embeddings')
    with op.batch_alter_table('context_dependencies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_context_dependencies_id'))

    op.drop_table('context_dependencies')
    with op.batch_alter_table('workspace_variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_variables_id'))

    op.drop_table('workspace_variables')
    with op.batch_alter_table('workspace_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspace_settings_id'))

    op.drop_table('workspace_settings')
    with op.batch_alter_table('templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_templates_id'))

    op.drop_table('templates')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_id'))

    op.drop_table('journals')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('contexts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contexts_id'))

    op.drop_table('contexts')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analytics_events_id'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_id'))

    op.drop_table('workspaces')
    with op.batch_alter_table('variables', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variables_id'))

    op.drop_table('variables')
    with op.batch_alter_table('tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tags_id'))

    op.drop_table('tags')
    op.drop_table('settings')
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_providers_id'))

    op.drop_table('providers')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_id'))

    op.drop_table('favorites')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
